package common;

public enum PageType {
	USER_MANAGEMENT_PAGE,
	HOME_PAGE,
	ADD_VIDEO,
	ADD_VIDEO_DETAIL,
	WATCH_VIDEO,
	ADMIN_HOME,
	ADMIN_LIST_VIDEO,
	HOME_RECOMEND_VIDEO,
	HOME_FAVORITE_VIDEO,
	ADMIN_LIST_USER, SEARCH, ADMIN_ADD_USER
}
